name: PR Auto Label Action
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
jobs:
  pr-auto-label-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: tobytheghost/pr-auto-label-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}